from __future__ import annotations

DOMAIN = "hydros"
CONF_USERNAME = "username"
CONF_PASSWORD = "password"
CONF_REGION = "region"
CONF_COLLECTIVES = "collectives"
CONF_ENABLE_REMOTE_CONTROL = "enable_remote_control"
CONF_ACCEPT_REMOTE_CONTROL_DISCLAIMER = "accept_remote_control_disclaimer"
CONF_ENABLE_ALEXA_SCENES = "enable_alexa_scenes"
CONF_ALEXA_EASY_SETUP = "alexa_easy_setup"
CONF_ALEXA_TARGET_COLLECTIVE = "alexa_target_collective"
CONF_ALEXA_FEED_SCENE_NAME = "alexa_feed_scene_name"
CONF_ALEXA_FEED_SCENE_MODE = "alexa_feed_scene_mode"
CONF_ALEXA_FEED_RETURN_ENABLED = "alexa_feed_return_enabled"
CONF_ALEXA_FEED_RETURN_DELAY_MINUTES = "alexa_feed_return_delay_minutes"
CONF_ALEXA_FEED_RETURN_MODE = "alexa_feed_return_mode"
CONF_ALEXA_MAINT_SCENE_NAME = "alexa_maint_scene_name"
CONF_ALEXA_MAINT_SCENE_MODE = "alexa_maint_scene_mode"
CONF_ALEXA_MAINT_RETURN_ENABLED = "alexa_maint_return_enabled"
CONF_ALEXA_MAINT_RETURN_DELAY_MINUTES = "alexa_maint_return_delay_minutes"
CONF_ALEXA_MAINT_RETURN_MODE = "alexa_maint_return_mode"
CONF_ALEXA_CUSTOM_SCENE_NAME = "alexa_custom_scene_name"
CONF_ALEXA_CUSTOM_SCENE_MODE = "alexa_custom_scene_mode"
CONF_ALEXA_CUSTOM_RETURN_ENABLED = "alexa_custom_return_enabled"
CONF_ALEXA_CUSTOM_RETURN_DELAY_MINUTES = "alexa_custom_return_delay_minutes"
CONF_ALEXA_CUSTOM_RETURN_MODE = "alexa_custom_return_mode"
DEFAULT_REGION = "us-west-2"
DEFAULT_WATCHDOG_INACTIVITY = 5
DEFAULT_COMMAND_CONFIRM_TIMEOUT = 15
DEFAULT_OUTPUT_COMMAND_COOLDOWN_SECONDS = 1.0
DEFAULT_MODE_COMMAND_COOLDOWN_SECONDS = 2.0
DEFAULT_MAX_MANUAL_DOSE_SECONDS = 1800
DEFAULT_AVAILABILITY_WINDOW_SECONDS = 360  # 6 minutes; slightly longer than the 5-minute watchdog
DEFAULT_ENABLE_ALEXA_SCENES = True
DEFAULT_ALEXA_EASY_SETUP = True
DEFAULT_ALEXA_FEED_SCENE_NAME = "Feed Mode"
DEFAULT_ALEXA_FEED_SCENE_MODE = "Feeding"
DEFAULT_ALEXA_FEED_RETURN_ENABLED = True
DEFAULT_ALEXA_FEED_RETURN_DELAY_MINUTES = 15
DEFAULT_ALEXA_FEED_RETURN_MODE = "Normal"
DEFAULT_ALEXA_MAINT_SCENE_NAME = "Maintenance Mode"
DEFAULT_ALEXA_MAINT_SCENE_MODE = "Maintenance"
DEFAULT_ALEXA_MAINT_RETURN_ENABLED = False
DEFAULT_ALEXA_MAINT_RETURN_DELAY_MINUTES = 30
DEFAULT_ALEXA_MAINT_RETURN_MODE = "Normal"
DEFAULT_ALEXA_CUSTOM_SCENE_NAME = ""
DEFAULT_ALEXA_CUSTOM_SCENE_MODE = ""
DEFAULT_ALEXA_CUSTOM_RETURN_ENABLED = False
DEFAULT_ALEXA_CUSTOM_RETURN_DELAY_MINUTES = 15
DEFAULT_ALEXA_CUSTOM_RETURN_MODE = "Normal"

PLATFORMS: list[str] = ["sensor", "binary_sensor", "button", "select", "switch", "number", "scene"]

SIGNAL_COLLECTIVE_UPDATED = "hydros_collective_updated_{entry}_{thing}"
SIGNAL_CONFIG_UPDATED = "hydros_config_updated_{entry}_{thing}"

SERVICE_SET_OUTPUT_STATE = "set_output_state"
SERVICE_SET_PUMP_SPEED = "set_pump_speed"
SERVICE_CHANGE_MODE = "change_mode"
SERVICE_MANUAL_DOSE = "manual_dose"
